cache:
  key: test_npm
  paths:
    - node_modules

before_script:
  - npm config set unsafe-perm true
  - npm i

test_npm:
  stage: test
  image: node:lts
  tags:
    - docker
  script:
    - npm run test
