apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kuserver-server.fullname" . }}-kuserver
  labels:
    app: {{ template "kuserver-server.name" . }}
    chart: {{ template "kuserver-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key,$value := .Values.kuserver.env }}
  {{ $key | lower }}: {{ $value | b64enc | quote }}
  {{- end }}
