{{- if or .Values.web.enabled .Values.thumbor.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "kuserver-server.fullname" . }}
  labels:
    app: {{ template "kuserver-server.name" . }}
    chart: {{ template "kuserver-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    layer: ingress
  annotations:
{{- if .Values.web.CERT_MANAGER_AVAILABLE }}
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: 10240m
{{- end }}
{{- if .Values.ingress.ip }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.ip | quote }}
{{- end }}
spec:
{{- if .Values.web.CERT_MANAGER_AVAILABLE }}
  tls:
    - hosts:
      - {{ .Values.web.host | quote }}
      secretName: live-kuserver-com
    - hosts:
      - {{ .Values.thumbor.media | quote }}
      secretName: media-tls
{{- end }}
  rules:
{{- if .Values.web.enabled }}
    - host: {{ .Values.web.host | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ template "kuserver-server.fullname" . }}-web
              servicePort: node-server
{{- end }}
{{- if .Values.thumbor.enabled }}
    - host: {{ .Values.thumbor.media | quote }}
      http:
        paths:
          - backend:
              serviceName: {{ template "kuserver-server.fullname" . }}-thumbor
              servicePort: thumbor
{{- end }}
{{- end -}}
