apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
spec:
  secretName: test-cert-tls
  issuerRef:
    name: letsencrypt-staging-dns
    kind: ClusterIssuer
  dnsNames:
  - test.kuserver.com
  acme:
    config:
    - dns01:
        provider: clouddns
      domains:
      - test.kuserver.com
