{{- if .Values.mongo.enabled -}}
{{- if .Values.mongo.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "kuserver-server.fullname" . }}-mongo
  labels:
    app: {{ template "kuserver-server.name" . }}
    chart: {{ template "kuserver-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    layer: mongo
spec:
  accessModes:
  - {{ .Values.mongo.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.mongo.persistence.size | quote }}
{{- if .Values.mongo.persistence.storageClass }}
{{- if (eq "-" .Values.mongo.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.mongo.persistence.storageClass | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
