apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kuserver-server.fullname" . }}-mongo
  labels:
    app: {{ template "kuserver-server.name" . }}
    chart: {{ template "kuserver-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    layer: mongo
type: Opaque
data:
  mongo-password: {{ .Values.mongo.password | b64enc | quote }}
